const buses = [
    {
      id: '214',
      name: 'React Seyahat',
      depatureTime: '18:30',
      arrivalTime: '06:15',
      price: '1000',
      boardingPoints: ['İstanbul', 'Ankara', 'Bursa', 'İzmir'],
      droppingPoints: ['Antalya', 'Ayvalık', 'Asos', 'Fethiye'],
      seats: [
        { no: 1, isBooked: false, gender:'female'},
        { no: 2, isBooked: true, gender:'male' },
        { no: 3, isBooked: false, gender:'male' },
        { no: 4, isBooked: false, gender:'male' },
        { no: '5', isBooked: false, gender:'male' },
        { no: '6', isBooked: true, gender:'female' },
        { no: '7', isBooked: false, gender:'female' },
        { no: '8', isBooked: true, gender:'male' },
        { no: '9', isBooked: false, gender:'male' },
        { no: '10', isBooked: true, gender:'female' },
        { no: '11', isBooked: false, gender:'female' },
        { no: '12', isBooked: true, gender:'male' },
      ],
    },
    {
      id: '102',
      name: 'React Seyahat',
      depatureTime: '22:30',
      arrivalTime: '08:15',
      price: '1000',
      boardingPoints: ['İstanbul', 'Ankara', 'Bursa', 'İzmir'],
      droppingPoints: ['Antalya', 'Ayvalık', 'Asos', 'Fethiye'],
    },
    {
      id: '786',
      name: 'React Seyahat',
      depatureTime: '22:30',
      arrivalTime: '08:15',
      price: '1000',
      boardingPoints: ['İstanbul', 'Ankara', 'Bursa', 'İzmir'],
      droppingPoints: ['Antalya', 'Ayvalık', 'Asos', 'Fethiye'],
    },
    {
      id: '618',
      name: 'React Seyahat',
      depatureTime: '22:30',
      arrivalTime: '08:15',
      price: '1000',
      boardingPoints: ['İstanbul', 'Ankara', 'Bursa', 'İzmir'],
      droppingPoints: ['Antalya', 'Ayvalık', 'Asos', 'Fethiye'],
    },
    {
      id: '188',
      name: 'React Seyahat',
      depatureTime: '22:30',
      arrivalTime: '08:15',
      price: '1000',
      boardingPoints: ['İstanbul', 'Ankara', 'Bursa', 'İzmir'],
      droppingPoints: ['Antalya', 'Ayvalık', 'Asos', 'Fethiye'],
    },
  ]

export default buses;